# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/devcontainers/typescript-node:22

# Preinstall required global tools as root so non-root user doesn't need sudo
RUN npm i -g @openai/codex@latest


